name: myapp
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0" # Menyesuaikan versi SDK agar kompatibel dengan Flutter 3.5.3

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Menggunakan lint versi terbaru

flutter:
  uses-material-design: true
